name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: |
          mkdir -p coverage
          yarn check > coverage/test-results.txt || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/test-results.txt

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: coverage

      - name: Display test results
        run: cat coverage/test-results.txt

      - name: Deploy
        run: |
          ls -a

          echo "Check PM2 status"
          pm2 status

          echo "Delete the node-app process"
          pm2 delete node-app || true

          echo "Start the node-app process"
          pm2 start "yarn start" --name="node-app"

          echo "Save the process list"
          pm2 save

          echo "Deployment completed."
